// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8Bm2nA3d3kjY2Ghb_OoyOqCHgFJnKQI',
    appId: '1:447012714240:web:290ed6578f4fef64efa5e5',
    messagingSenderId: '447012714240',
    projectId: 'menotes-de22f',
    authDomain: 'menotes-de22f.firebaseapp.com',
    storageBucket: 'menotes-de22f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1P6AIjZp6RVbHehWuQcBBnNiBCpiv5e4',
    appId: '1:447012714240:android:b410bb99fd658542efa5e5',
    messagingSenderId: '447012714240',
    projectId: 'menotes-de22f',
    storageBucket: 'menotes-de22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iv7NxEqE4mFPBb8brEGVpsk0N-CUGtM',
    appId: '1:447012714240:ios:118869deb4246225efa5e5',
    messagingSenderId: '447012714240',
    projectId: 'menotes-de22f',
    storageBucket: 'menotes-de22f.appspot.com',
    iosBundleId: 'com.example.menotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iv7NxEqE4mFPBb8brEGVpsk0N-CUGtM',
    appId: '1:447012714240:ios:1ee620ea3285c3ffefa5e5',
    messagingSenderId: '447012714240',
    projectId: 'menotes-de22f',
    storageBucket: 'menotes-de22f.appspot.com',
    iosBundleId: 'com.example.menotes.RunnerTests',
  );
}
